[package]
name = "yew-query"
description = "A future data observed for yew inspired in React Query"
license = "MIT"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
yew = "0.19.3"
futures = "0.3.25"