[package]
name = "yew-query"
description = "A future data observer for yew"
keywords = ["wasm", "async"]
license = "MIT"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
yew-query-core = { path = "../yew-query-core" }
yew = { version = "0.20", features = ["csr"] }
futures = "0.3.25"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"

# TODO: Add logging as a feature
log = "0.4.17"

[dependencies.web-sys]
version = "0.3.60"
features = ["AbortController", "AbortSignal", "Navigator"]

[dependencies.instant]
version = "0.1"
features = ["wasm-bindgen", "inaccurate"]

[dev-dependencies]
wasm-bindgen-test = "0.3"
gloo-utils = "0.1.6"
